### ISSUE TITLE
[Meta] Disable ACRA crash reports to main Tachiyomi crash reporting endpoint

### ISSUE THREAD

**Issue by arkon** [Rattlehead15/tachiyomiOCR#2]
Hi there,

Nice work with your fork!

I've started noticing crash reports in our system originating from your fork. Can you either disable ACRA or point it to a different instance?

cf. https://github.com/Rattlehead15/tachiyomiOCR/blob/master/app/src/main/java/eu/kanade/tachiyomi/App.kt#L31

**Comment by Rattlehead15** [comment]
Hey, I'm glad you liked it!
Sorry for that, it's the first time I've forked an android app and I'm not really sure what needs to be changed. I'll be fixing this as soon as possible, is there any other thing that I should modify so as to not bother you guys anymore?

**Comment by arkon** [comment]
Good question. I've compiled a list of things that should be changed here: https://github.com/tachiyomiorg/tachiyomi/blob/master/CONTRIBUTING.md#forks

**Comment by Rattlehead15** [comment]
Sorry, but do I really have to change the package name or can I just change the applicationId? I'm asking because changing the package name seems to break the installing of extensions since it can't find some classes

**Comment by arkon** [comment]
Sorry, yes I meant the `applicationId`. However, it'll affect your existing installations.

**Comment by Rattlehead15** [comment]
Alright I think it's all done now, except for the icon which I'll have to spend some time on. Thanks for taking the time to make the checklist. Also, it's possible some people won't see this update and will keep sending crash reports so really sorry for that.

**Comment by arkon** [comment]
Your changes look good, but make sure to disable or change the ACRA endpoint too.

**Comment by Rattlehead15** [comment]
oh my bad I forgot to disable it
